'use client'
import { AuthContext } from "@/components/context/AuthProvider";
import Sidebar from "@/components/sidebar/Sidebar";
import { Inter } from "next/font/google";
import { useContext } from "react";
import { FaRegUserCircle } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Estarch",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({ children }) {

  const {authUser} = useContext(AuthContext)


  return (
    <div className="grid md:grid-cols-12 md:mx-12 my-4 ">
      <div className="breadcrumbs text-sm lg:col-span-2 md:col-span-4 hidden md:block">
        <ul>
          <li><p className="cursor-pointer">Home</p></li>
          <li><p className="cursor-pointer">My Account</p> </li>
        </ul>
      </div>
      <div className="lg:col-span-10 md:col-span-8 mx-4">
        <h1 className="md:flex items-center gap-4 text-2xl font-bold hidden "><span className="text-2xl"><FaRegUserCircle /></span>Hello, {authUser?.fullName}</h1>
      </div>
      <div className="lg:col-span-2 md:col-span-4 mt-6 md:mr-4"><Sidebar /></div>
      <div className="lg:col-span-10 md:col-span-8 mt-6 mx-4">{children}</div>
    </div>
  );
}
